[package]
name = "randomduck/astro-static-site-a12"
version = "0.1.0"
description = "wasmer-tests/wasmer-edge-astro-sample website"
repository = "https://github.com/ayys/astro-static-site-a12"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
